import z from "zod";
import "zod-openapi/extend";

export const companyNotificationEmailAddressResponse = z.object({
    id: z.string().openapi({
        description: "The ID of the notification email address record. Use it with the get, update and delete notification email address endpoints.",
        example: "cnea_01JQZ8X0M4T7RB6K9V2NDHW3PA",
    }),
    companyId: z.string().openapi({
        description: "The ID of the company these notifications are sent for.",
        example: "c_01JQZ8X0M4T7RB6K9V2NDHW3PA",
    }),
    email: z.string().openapi({
        description: "The address the notifications are sent to.",
        example: "billing@example.com",
    }),
    notifyIncoming: z.boolean().openapi({
        description: "Whether this address is notified when the company receives a document.",
        example: true,
    }),
    notifyOutgoing: z.boolean().openapi({
        description: "Whether this address is notified when the company sends a document.",
        example: false,
    }),
    includeAutoGeneratedPdfIncoming: z.boolean().openapi({
        description: "Whether the notification for an incoming document carries a PDF rendering of it as an attachment.",
        example: true,
    }),
    includeAutoGeneratedPdfOutgoing: z.boolean().openapi({
        description: "Whether the notification for an outgoing document carries a PDF rendering of it as an attachment.",
        example: false,
    }),
    includeDocumentJsonIncoming: z.boolean().openapi({
        description: "Whether the notification for an incoming document carries the document's JSON representation as an attachment.",
        example: false,
    }),
    includeDocumentJsonOutgoing: z.boolean().openapi({
        description: "Whether the notification for an outgoing document carries the document's JSON representation as an attachment.",
        example: false,
    }),
    createdAt: z.string().datetime().openapi({
        description: "When the address was added to the company.",
    }),
    updatedAt: z.string().datetime().openapi({
        description: "When the address was last changed.",
    }),
});
