import { Server, type Context } from "@recommand/lib/api";
import { z } from "zod";
import "zod-openapi/extend";
import { zodValidator } from "@recommand/lib/zod-validator";
import { actionFailure } from "@recommand/lib/utils";
import { type AuthenticatedTeamContext, type AuthenticatedUserContext } from "@core/lib/auth-middleware";
import { describeRoute } from "hono-openapi";
import { getTransmittedDocument } from "@peppol/data/transmitted-documents";
import {
    hydrateDocumentParsedAttachments,
    originalPayloadFilename,
    resolveDocumentOriginalPayload,
    resolveDocumentXmlAndAttachments,
} from "@peppol/data/offload/storage";
import {
    describeErrorResponse,
} from "@core/lib/api-docs";
import { requireIntegrationSupportedTeamAccess, type CompanyAccessContext } from "@peppol/utils/auth-middleware";
import JSZip from "jszip";
import { renderDocumentPdf } from "@peppol/utils/document-renderer";

const server = new Server();

const downloadPackageRouteDescription = describeRoute({
    operationId: "downloadPackage",
    description: "Download a document as a zip file containing the document JSON, XML, and any binary attachments. Optionally include an autogenerated PDF based on the generatePdf query parameter.",
    summary: "Download Document Package",
    tags: ["Documents"],
    responses: {
        "200": {
            description: "Successfully downloaded the document",
            content: {
                "application/zip": {
                    schema: {
                        type: "string",
                        format: "binary",
                    },
                },
            },
        },
        ...describeErrorResponse(404, "Document not found"),
        ...describeErrorResponse(500, "Failed to download document"),
    },
});

const downloadPackageParamSchema = z.object({
    documentId: z.string().openapi({
        description: "The ID of the document to download",
    }),
});

const downloadPackageParamSchemaWithTeamId = downloadPackageParamSchema.extend({
    teamId: z.string(),
});

const downloadPackageQuerySchema = z.object({
    generatePdf: z.enum(["never", "always", "when_no_pdf_attachment"]).default("never").openapi({
        description: "When to include the autogenerated PDF in the package",
        example: "never",
    }),
});

type DownloadPackageContext = Context<AuthenticatedUserContext & AuthenticatedTeamContext & CompanyAccessContext, string, { in: { param: z.input<typeof downloadPackageParamSchemaWithTeamId>, query: z.input<typeof downloadPackageQuerySchema> }, out: { param: z.infer<typeof downloadPackageParamSchemaWithTeamId>, query: z.infer<typeof downloadPackageQuerySchema> } }>;

const _downloadPackageMinimal = server.get(
    "/documents/:documentId/download-package",
    requireIntegrationSupportedTeamAccess(),
    downloadPackageRouteDescription,
    zodValidator("param", downloadPackageParamSchema),
    zodValidator("query", downloadPackageQuerySchema),
    _downloadPackageImplementation,
);

const _downloadPackage = server.get(
    "/:teamId/documents/:documentId/downloadPackage",
    requireIntegrationSupportedTeamAccess(),
    describeRoute({hide: true}),
    zodValidator("param", downloadPackageParamSchemaWithTeamId),
    zodValidator("query", downloadPackageQuerySchema),
    _downloadPackageImplementation,
);

async function _downloadPackageImplementation(c: DownloadPackageContext) {
    try {
        const { documentId } = c.req.valid("param");
        const { generatePdf } = c.req.valid("query");
        const document = await getTransmittedDocument(c.var.team.id, documentId);

        if (!document) {
            return c.json(actionFailure("Document not found"), 404);
        }

        // Create a new zip file
        const zip = new JSZip();

        const [{ xml, attachments }, originalPayload] = await Promise.all([
            resolveDocumentXmlAndAttachments(document),
            resolveDocumentOriginalPayload(document),
        ]);

        const parsed = hydrateDocumentParsedAttachments(document.parsed, attachments);

        // Add document metadata as JSON
        const {
            xml: _xml,
            xmlLocation,
            attachmentsLocation,
            originalPayloadLocation,
            originalPayloadContainerFormat,
            s3KeyPrefix,
            ...documentMetadata
        } = { ...document, parsed };
        zip.file("document.json", JSON.stringify(documentMetadata, null, 2));

        // Add XML if available
        if (xml) {
            zip.file("document.xml", xml);
        }

        if (originalPayload) {
            zip.file(originalPayloadFilename(document.originalPayloadContainerFormat), originalPayload);
        }

        // If there are attachments, add them to the zip
        let hasPdfAttachment = false;
        if (attachments) {
            for (const attachment of attachments) {
                const base64 = attachment.embeddedDocument;
                const mimeCode = attachment.mimeCode;
                const filename = attachment.filename;

                if (base64 && mimeCode && filename) {
                    zip.file(filename, Buffer.from(base64, 'base64'));
                    if (mimeCode === "application/pdf") {
                        hasPdfAttachment = true;
                    }
                }
            }
        }

        // Conditionally generate and add PDF based on the generatePdf flag
        const shouldgeneratePdf = generatePdf === "always" || (generatePdf === "when_no_pdf_attachment" && !hasPdfAttachment);
        
        if (shouldgeneratePdf) {
            try {
                const pdfBuffer = await renderDocumentPdf(document);
                zip.file("auto-generated.pdf", pdfBuffer);
            } catch (error) {
                // If PDF generation fails, we still want to return the rest of the package
                console.error("Failed to generate PDF for document package:", error);
            }
        }

        // Generate the zip file
        const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

        // Set headers for file download
        c.header("Content-Type", "application/zip");
        c.header("Content-Disposition", `attachment; filename="${documentId}.zip"`);

        return c.body(zipBuffer);
    } catch (error) {
        return c.json(actionFailure("Failed to download document"), 500);
    }
}

export type DownloadPackage = typeof _downloadPackage | typeof _downloadPackageMinimal;

export default server;
