import { z } from "zod";
import { registerEventType } from "@core/data/rules/events";
import type { EventTypeDefinition } from "@core/lib/rules/types";
import {
  buildCompanyVerificationNotificationProps,
  buildDocumentLabelNotificationProps,
  buildIncomingDocumentNotificationProps,
  buildOutgoingDocumentNotificationProps,
  buildPeppolDocumentEmailAttachments,
} from "@peppol/data/email/document-notification-props";

const receivedDocumentTypes = [
  "invoice",
  "creditNote",
  "selfBillingInvoice",
  "selfBillingCreditNote",
  "messageLevelResponse",
  "frenchInvoicingCdar",
  "frenchB2CSalesReport",
  "frenchB2CPaymentReport",
  "unknown",
] as const;

/**
 * English labels for the document type enum, used by the rule editor's value
 * dropdowns. The enum values are code identifiers, so they are not translation
 * keys — these labels are. Keep them identical to getDocumentTypeLabel() in
 * @peppol/lib/client/document-type-labels, which is what the rest of the UI
 * renders; the Record type keeps this list exhaustive.
 */
const documentTypeLabels: Record<(typeof receivedDocumentTypes)[number], string> = {
  invoice: "Invoice",
  creditNote: "Credit Note",
  selfBillingInvoice: "Self Billing Invoice",
  selfBillingCreditNote: "Self Billing Credit Note",
  messageLevelResponse: "Message Level Response",
  frenchInvoicingCdar: "French Invoicing CDAR",
  frenchB2CSalesReport: "French B2C Sales Report",
  frenchB2CPaymentReport: "French B2C Payment Report",
  unknown: "Unknown",
};

const verificationStatuses = ["verified", "rejected", "error"] as const;

const verificationStatusLabels: Record<(typeof verificationStatuses)[number], string> = {
  verified: "Verified",
  rejected: "Rejected",
  error: "Error",
};

type ConditionField = EventTypeDefinition["conditionFields"][number];

const documentTypeField: ConditionField = {
  path: "payload.docType",
  label: "Document type",
  valueType: "enum",
  operators: ["eq", "neq", "in", "notIn"],
  enumValues: [...receivedDocumentTypes],
  enumLabels: documentTypeLabels,
};

const documentReceivedPayloadSchema = z.object({
  companyId: z.string(),
  docType: z.enum(receivedDocumentTypes),
  senderId: z.string(),
  receiverId: z.string(),
  peppolMessageId: z.string().nullable().optional(),
  peppolConversationId: z.string().nullable().optional(),
  envelopeId: z.string().nullable().optional(),
  countryC1: z.string(),
});

const documentSentPayloadSchema = z.object({
  companyId: z.string(),
  docType: z.enum(receivedDocumentTypes),
  senderId: z.string(),
  receiverId: z.string().nullable(),
  peppolMessageId: z.string().nullable().optional(),
  peppolConversationId: z.string().nullable().optional(),
  envelopeId: z.string().nullable().optional(),
  countryC1: z.string(),
});

const documentLabelPayloadSchema = z.object({
  companyId: z.string(),
  labelId: z.string(),
  labelExternalId: z.string().nullable().optional(),
  docType: z.enum(receivedDocumentTypes),
  senderId: z.string(),
  // Label events are emitted from stored transmitted documents, whose receiverId
  // can be null for non-Peppol or email-only document rows.
  receiverId: z.string().nullable(),
});

const companyVerificationPayloadSchema = z.object({
  companyId: z.string(),
  status: z.enum(verificationStatuses),
  errorMessage: z.string().nullable().optional(),
});

const documentEmailAttachments = [
  { key: "embeddedAttachments", label: "Embedded attachments" },
  { key: "xmlDocument", label: "XML document" },
  { key: "autoGeneratedPdf", label: "Auto-generated PDF" },
  { key: "documentJson", label: "document.json" },
];

let registered = false;

export function registerPeppolEventTypes() {
  if (registered) {
    return;
  }

  registered = true;

  registerEventType({
    type: "peppol.document.received.v1",
    aggregateType: "peppol.document",
    payload: documentReceivedPayloadSchema,
    conditionFields: [
      { path: "payload.companyId", label: "Company", valueType: "string", operators: ["eq", "neq", "in"], picker: "company" },
      documentTypeField,
      { path: "payload.senderId", label: "Sender address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
      { path: "payload.receiverId", label: "Receiver address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
    ],
    webhook: {
      eventType: "document.received",
      project: (event) => ({
        eventType: "document.received",
        documentId: event.aggregateId,
        teamId: event.teamId,
        companyId: (event.payload as z.infer<typeof documentReceivedPayloadSchema>).companyId,
      }),
    },
    email: {
      template: "document-incoming-notification",
      attachments: documentEmailAttachments,
      buildProps: buildIncomingDocumentNotificationProps,
      buildAttachments: buildPeppolDocumentEmailAttachments,
    },
    ui: {
      label: "Document received",
      description: "A document was received for a company",
      group: "Documents",
    },
  });

  registerEventType({
    type: "peppol.document.sent.v1",
    aggregateType: "peppol.document",
    payload: documentSentPayloadSchema,
    conditionFields: [
      { path: "payload.companyId", label: "Company", valueType: "string", operators: ["eq", "neq", "in"], picker: "company" },
      documentTypeField,
      { path: "payload.senderId", label: "Sender address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
      { path: "payload.receiverId", label: "Receiver address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
    ],
    webhook: {
      eventType: "document.sent",
      project: (event) => ({
        eventType: "document.sent",
        documentId: event.aggregateId,
        teamId: event.teamId,
        companyId: (event.payload as z.infer<typeof documentSentPayloadSchema>).companyId,
      }),
    },
    email: {
      template: "document-outgoing-notification",
      attachments: documentEmailAttachments,
      buildProps: buildOutgoingDocumentNotificationProps,
      buildAttachments: buildPeppolDocumentEmailAttachments,
    },
    ui: {
      label: "Document sent",
      description: "A document was sent by a company",
      group: "Documents",
    },
  });

  registerEventType({
    type: "peppol.document.label.assigned.v1",
    aggregateType: "peppol.document",
    payload: documentLabelPayloadSchema,
    conditionFields: [
      { path: "payload.companyId", label: "Company", valueType: "string", operators: ["eq", "neq", "in"], picker: "company" },
      { path: "payload.labelId", label: "Label", valueType: "string", operators: ["eq", "neq", "in"], picker: "label" },
      { path: "payload.labelExternalId", label: "Label external ID", valueType: "string", operators: ["eq", "neq", "in"] },
      documentTypeField,
      { path: "payload.senderId", label: "Sender address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
      { path: "payload.receiverId", label: "Receiver address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
    ],
    webhook: {
      eventType: "document.label.assigned",
      project: (event) => {
        const payload = event.payload as z.infer<typeof documentLabelPayloadSchema>;
        return {
          eventType: "document.label.assigned",
          documentId: event.aggregateId,
          teamId: event.teamId,
          companyId: payload.companyId,
          labelId: payload.labelId,
        };
      },
    },
    email: {
      template: "document-label-assigned-notification",
      buildProps: buildDocumentLabelNotificationProps,
      attachments: documentEmailAttachments,
      buildAttachments: buildPeppolDocumentEmailAttachments,
    },
    ui: {
      label: "Document label assigned",
      group: "Documents",
    },
  });

  registerEventType({
    type: "peppol.document.label.unassigned.v1",
    aggregateType: "peppol.document",
    payload: documentLabelPayloadSchema,
    conditionFields: [
      { path: "payload.companyId", label: "Company", valueType: "string", operators: ["eq", "neq", "in"], picker: "company" },
      { path: "payload.labelId", label: "Label", valueType: "string", operators: ["eq", "neq", "in"], picker: "label" },
      { path: "payload.labelExternalId", label: "Label external ID", valueType: "string", operators: ["eq", "neq", "in"] },
      documentTypeField,
      { path: "payload.senderId", label: "Sender address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
      { path: "payload.receiverId", label: "Receiver address", valueType: "string", operators: ["eq", "neq", "in", "notIn"] },
    ],
    webhook: {
      eventType: "document.label.unassigned",
      project: (event) => {
        const payload = event.payload as z.infer<typeof documentLabelPayloadSchema>;
        return {
          eventType: "document.label.unassigned",
          documentId: event.aggregateId,
          teamId: event.teamId,
          companyId: payload.companyId,
          labelId: payload.labelId,
        };
      },
    },
    email: {
      template: "document-label-unassigned-notification",
      buildProps: buildDocumentLabelNotificationProps,
      attachments: documentEmailAttachments,
      buildAttachments: buildPeppolDocumentEmailAttachments,
    },
    ui: {
      label: "Document label unassigned",
      group: "Documents",
    },
  });

  registerEventType({
    type: "peppol.company.verification.v1",
    aggregateType: "peppol.company",
    payload: companyVerificationPayloadSchema,
    conditionFields: [
      { path: "payload.companyId", label: "Company", valueType: "string", operators: ["eq", "neq", "in"], picker: "company" },
      { path: "payload.status", label: "Verification status", valueType: "enum", operators: ["eq", "neq", "in", "notIn"], enumValues: [...verificationStatuses], enumLabels: verificationStatusLabels },
      { path: "payload.errorMessage", label: "Error message", valueType: "string", operators: ["eq", "neq", "exists"] },
    ],
    webhook: {
      eventType: "company.verification",
      project: (event) => {
        const payload = event.payload as z.infer<typeof companyVerificationPayloadSchema>;
        return Object.fromEntries(
          Object.entries({
            eventType: "company.verification",
            teamId: event.teamId,
            companyId: payload.companyId,
            status: payload.status,
            errorMessage: payload.errorMessage ?? undefined,
          }).filter(([, value]) => value !== undefined)
        );
      },
    },
    email: {
      template: "company-verification-notification",
      buildProps: buildCompanyVerificationNotificationProps,
    },
    ui: {
      label: "Company verification",
      description: "A company verification finished",
      group: "Companies",
    },
  });
}
