import z from "zod";
import "zod-openapi/extend";

export const responseCodeSchema = z.enum(["AB", "AP", "RE"]);

export const messageLevelResponseSchema = z.object({
    id: z.string(),
    issueDate: z.string().date().openapi({ example: "2024-03-20" }),
    responseCode: responseCodeSchema.openapi({ description: "The response code of the message level response (AB: Message acknowledgement, AP: Accepted, RE: Rejected)", example: "AB" }),
    envelopeId: z.string().openapi({ description: "Identifies the document on which the message level response is based."}),
}).openapi({ ref: "MessageLevelResponse", title: "Message Level Response", description: "Message Level Response received from a recipient" });

export const sendMessageLevelResponseSchema = messageLevelResponseSchema.extend({
    id: z.string().optional().openapi({
        description: "The ID of the message level response. If not provided, the ID will be autogenerated.",
    }),
    issueDate: z.string().date().optional().openapi({
        example: "2024-03-20",
        description: "If not provided, the issue date will be the current date.",
    }),
}).openapi({ ref: "SendMessageLevelResponse", title: "Message Level Response to send", description: "Message Level Response to send to a recipient" });

export type MessageLevelResponse = z.infer<typeof messageLevelResponseSchema>;
export type SendMessageLevelResponse = z.infer<typeof sendMessageLevelResponseSchema>;