import { z } from "zod";

export const ISO_ICD_SCHEME_IDENTIFIERS: { key: string, name: string }[] = [
  { key: '0002', name: 'System Information et Repertoire des Entreprise et des Etablissements: SIRENE' },
  { key: '0003', name: 'Codification Numerique des Etablissments Financiers En Belgique' },
  { key: '0004', name: 'NBS/OSI NETWORK' },
  { key: '0005', name: 'USA FED GOV OSI NETWORK' },
  { key: '0006', name: 'USA DOD OSI NETWORK' },
  { key: '0007', name: 'Organisationsnummer' },
  { key: '0008', name: 'LE NUMERO NATIONAL' },
  { key: '0009', name: 'SIRET-CODE' },
  { key: '0010', name: 'Organizational Identifiers for Structured Names under ISO 9541 Part 2' },
  { key: '0011', name: 'International Code Designator for the Identification of OSI-based, Amateur Radio Organizations, Network Objects and Application Services' },
  { key: '0012', name: 'European Computer Manufacturers Association: ECMA' },
  { key: '0013', name: 'VSA FTP CODE (FTP = File Transfer Protocol)' },
  { key: '0014', name: 'NIST/OSI Implememts\' Workshop' },
  { key: '0015', name: 'Electronic Data Interchange: EDI' },
  { key: '0016', name: 'EWOS Object Identifiers' },
  { key: '0017', name: 'COMMON LANGUAGE' },
  { key: '0018', name: 'SNA/OSI Network' },
  { key: '0019', name: 'Air Transport Industry Services Communications Network' },
  { key: '0020', name: 'European Laboratory for Particle Physics: CERN' },
  { key: '0021', name: 'SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T.' },
  { key: '0022', name: 'OSF Distributed Computing Object Identification' },
  { key: '0023', name: 'Nordic University and Research Network: NORDUnet' },
  { key: '0024', name: 'Digital Equipment Corporation: DEC' },
  { key: '0025', name: 'OSI ASIA-OCEANIA WORKSHOP' },
  { key: '0026', name: 'NATO ISO 6523 ICDE coding scheme' },
  { key: '0027', name: 'Aeronautical Telecommunications Network (ATN)' },
  { key: '0028', name: 'International Standard ISO 6523' },
  { key: '0029', name: 'The All-Union Classifier of Enterprises and Organisations' },
  { key: '0030', name: 'AT&T/OSI Network' },
  { key: '0031', name: 'EDI Partner Identification Code' },
  { key: '0032', name: 'Telecom Australia' },
  { key: '0033', name: 'S G W OSI Internetwork' },
  { key: '0034', name: 'Reuter Open Address Standard' },
  { key: '0035', name: 'ISO 6523 - ICD' },
  { key: '0036', name: 'TeleTrust Object Identifiers' },
  { key: '0037', name: 'LY-tunnus' },
  { key: '0038', name: 'The Australian GOSIP Network' },
  { key: '0039', name: 'The OZ DOD OSI Network' },
  { key: '0040', name: 'Unilever Group Companies' },
  { key: '0041', name: 'Citicorp Global Information Network' },
  { key: '0042', name: 'DBP Telekom Object Identifiers' },
  { key: '0043', name: 'HydroNETT' },
  { key: '0044', name: 'Thai Industrial Standards Institute (TISI)' },
  { key: '0045', name: 'ICI Company Identification System' },
  { key: '0046', name: 'FUNLOC' },
  { key: '0047', name: 'BULL ODI/DSA/UNIX Network' },
  { key: '0048', name: 'OSINZ' },
  { key: '0049', name: 'Auckland Area Health' },
  { key: '0050', name: 'Firmenich' },
  { key: '0051', name: 'AGFA-DIS' },
  { key: '0052', name: 'Society of Motion Picture and Television Engineers (SMPTE)' },
  { key: '0053', name: 'Migros_Network M_NETOPZ' },
  { key: '0054', name: 'ISO6523 - ICDPCR' },
  { key: '0055', name: 'Energy Net' },
  { key: '0056', name: 'Nokia Object Identifiers (NOI)' },
  { key: '0057', name: 'Saint Gobain' },
  { key: '0058', name: 'Siemens Corporate Network' },
  { key: '0059', name: 'DANZNET' },
  { key: '0060', name: 'Data Universal Numbering System (D-U-N-S Number)' },
  { key: '0061', name: 'SOFFEX OSI' },
  { key: '0062', name: 'KPN OVN' },
  { key: '0063', name: 'ascomOSINet' },
  { key: '0064', name: 'UTC: Uniforme Transport Code' },
  { key: '0065', name: 'SOLVAY OSI CODING' },
  { key: '0066', name: 'Roche Corporate Network' },
  { key: '0067', name: 'ZellwegerOSINet' },
  { key: '0068', name: 'Intel Corporation OSI' },
  { key: '0069', name: 'SITA Object Identifier Tree' },
  { key: '0070', name: 'DaimlerChrysler Corporate Network' },
  { key: '0071', name: 'LEGO /OSI NETWORK' },
  { key: '0072', name: 'NAVISTAR/OSI Network' },
  { key: '0073', name: 'ICD Formatted ATM address' },
  { key: '0074', name: 'ARINC' },
  { key: '0075', name: 'Alcanet/Alcatel-Alsthom Corporate Network' },
  { key: '0076', name: 'Sistema Italiano di Identificazione di ogetti gestito da UNINFO' },
  { key: '0077', name: 'Sistema Italiano di Indirizzamento di Reti OSI Gestito da UNINFO' },
  { key: '0078', name: 'Mitel terminal or switching equipment' },
  { key: '0079', name: 'ATM Forum' },
  { key: '0080', name: 'UK National Health Service Scheme, (EDIRA compliant)' },
  { key: '0081', name: 'International NSAP' },
  { key: '0082', name: 'Norwegian Telecommunications Authority\'s, NTA\'S, EDI, identifier scheme (EDIRA compliant)' },
  { key: '0083', name: 'Advanced Telecommunications Modules Limited, Corporate Network' },
  { key: '0084', name: 'Athens Chamber of Commerce & Industry Scheme (EDIRA compliant)' },
  { key: '0085', name: 'Swiss Chambers of Commerce Scheme (EDIRA) compliant' },
  { key: '0086', name: 'United States Council for International Business (USCIB) Scheme, (EDIRA compliant)' },
  { key: '0087', name: 'National Federation of Chambers of Commerce & Industry of Belgium, Scheme (EDIRA compliant)' },
  { key: '0088', name: 'EAN Location Code' },
  { key: '0089', name: 'The Association of British Chambers of Commerce Ltd. Scheme, (EDIRA compliant)' },
  { key: '0090', name: 'Internet IP addressing - ISO 6523 ICD encoding' },
  { key: '0091', name: 'Cisco Systems / OSI Network' },
  { key: '0093', name: 'Revenue Canada Business Number Registration (EDIRA compliant)' },
  { key: '0094', name: 'DEUTSCHER INDUSTRIE- UND HANDELSTAG (DIHT) Scheme (EDIRA compliant)' },
  { key: '0095', name: 'Hewlett - Packard Company Internal AM Network' },
  { key: '0096', name: 'DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)' },
  { key: '0097', name: 'FTI - Ediforum Italia, (EDIRA compliant)' },
  { key: '0098', name: 'CHAMBER OF COMMERCE TEL AVIV-JAFFA Scheme (EDIRA compliant)' },
  { key: '0099', name: 'Siemens Supervisory Systems Network' },
  { key: '0100', name: 'PNG_ICD Scheme' },
  { key: '0101', name: 'South African Code Allocation' },
  { key: '0102', name: 'HEAG' },
  { key: '0104', name: 'BT - ICD Coding System' },
  { key: '0105', name: 'Portuguese Chamber of Commerce and Industry Scheme (EDIRA compliant)' },
  { key: '0106', name: 'Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)' },
  { key: '0107', name: 'Association of Swedish Chambers of Commerce and Industry Scheme (EDIRA compliant)' },
  { key: '0108', name: 'Australian Chambers of Commerce and Industry Scheme (EDIRA compliant)' },
  { key: '0109', name: 'BellSouth ICD AESA (ATM End System Address)' },
  { key: '0110', name: 'Bell Atlantic' },
  { key: '0111', name: 'Object Identifiers' },
  { key: '0112', name: 'ISO register for Standards producing Organizations' },
  { key: '0113', name: 'OriginNet' },
  { key: '0114', name: 'Check Point Software Technologies' },
  { key: '0115', name: 'Pacific Bell Data Communications Network' },
  { key: '0116', name: 'PSS Object Identifiers' },
  { key: '0117', name: 'STENTOR-ICD CODING SYSTEM' },
  { key: '0118', name: 'ATM-Network ZN\'96' },
  { key: '0119', name: 'MCI / OSI Network' },
  { key: '0120', name: 'Advantis' },
  { key: '0121', name: 'Affable Software Data Interchange Codes' },
  { key: '0122', name: 'BB-DATA GmbH' },
  { key: '0123', name: 'BASF Company ATM-Network' },
  { key: '0124', name: 'IOTA Identifiers for Organizations for Telecommunications Addressing using the ICD system format defined in ISO/IEC 8348' },
  { key: '0125', name: 'Henkel Corporate Network (H-Net)' },
  { key: '0126', name: 'GTE/OSI Network' },
  { key: '0127', name: 'Dresdner Bank Corporate Network' },
  { key: '0128', name: 'BCNR (Swiss Clearing Bank Number)' },
  { key: '0129', name: 'BPI (Swiss Business Partner Identification) code' },
  { key: '0130', name: 'Directorates of the European Commission' },
  { key: '0131', name: 'Code for the Identification of National Organizations' },
  { key: '0132', name: 'Certicom Object Identifiers' },
  { key: '0133', name: 'TC68 OID' },
  { key: '0134', name: 'Infonet Services Corporation' },
  { key: '0135', name: 'SIA Object Identifiers' },
  { key: '0136', name: 'Cable & Wireless Global ATM End-System Address Plan' },
  { key: '0137', name: 'Global AESA scheme' },
  { key: '0138', name: 'France Telecom ATM End System Address Plan' },
  { key: '0139', name: 'Savvis Communications AESA' },
  { key: '0140', name: 'Toshiba Organizations, Partners, And Suppliers\' (TOPAS) Code' },
  { key: '0141', name: 'NATO Commercial and Government Entity system' },
  { key: '0142', name: 'SECETI Object Identifiers' },
  { key: '0143', name: 'EINESTEINet AG' },
  { key: '0144', name: 'DoDAAC (Department of Defense Activity Address Code)' },
  { key: '0145', name: 'DGCP (Direction Générale de la Comptabilité Publique)administrative accounting identification scheme' },
  { key: '0146', name: 'DGI (Direction Générale des Impots) code' },
  { key: '0147', name: 'Standard Company Code' },
  { key: '0148', name: 'ITU (International Telecommunications Union)Data Network Identification Codes (DNIC)' },
  { key: '0149', name: 'Global Business Identifier' },
  { key: '0150', name: 'Madge Networks Ltd- ICD ATM Addressing Scheme' },
  { key: '0151', name: 'Australian Business Number (ABN) Scheme' },
  { key: '0152', name: 'Edira Scheme Identifier Code' },
  { key: '0153', name: 'Concert Global Network Services ICD AESA' },
  { key: '0154', name: 'Identification number of economic subjects: (ICO)' },
  { key: '0155', name: 'Global Crossing AESA (ATM End System Address)' },
  { key: '0156', name: 'AUNA' },
  { key: '0157', name: 'ATM interconnection with the Dutch KPN Telecom' },
  { key: '0158', name: 'Identification number of economic subject (ICO) Act on State Statistics of 29 November 2001, § 27' },
  { key: '0159', name: 'ACTALIS Object Identifiers' },
  { key: '0160', name: 'GTIN - Global Trade Item Number' },
  { key: '0161', name: 'ECCMA Open Technical Directory' },
  { key: '0162', name: 'CEN/ISSS Object Identifier Scheme' },
  { key: '0163', name: 'US-EPA Facility Identifier' },
  { key: '0164', name: 'TELUS Corporation' },
  { key: '0165', name: 'FIEIE Object identifiers' },
  { key: '0166', name: 'Swissguide Identifier Scheme' },
  { key: '0167', name: 'Priority Telecom ATM End System Address Plan' },
  { key: '0168', name: 'Vodafone Ireland OSI Addressing' },
  { key: '0169', name: 'Swiss Federal Business Identification Number. Central Business names Index (zefix) Identification Number' },
  { key: '0170', name: 'Teikoku Company Code' },
  { key: '0171', name: 'Luxembourg CP & CPS (Certification Policy and Certification Practice Statement) Index' },
  { key: '0172', name: 'Project Group "Lists of Properties" (PROLIST®)' },
  { key: '0173', name: 'eCI@ss' },
  { key: '0174', name: 'StepNexus' },
  { key: '0175', name: 'Siemens AG' },
  { key: '0176', name: 'Paradine GmbH' },
  { key: '0177', name: 'Odette International Limited' },
  { key: '0178', name: 'Route1 MobiNET' },
  { key: '0179', name: 'Penango Object Identifiers' },
  { key: '0180', name: 'Lithuanian military PKI' },
  { key: '0183', name: 'Numéro d\'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB)' },
  { key: '0184', name: 'DIGSTORG' },
  { key: '0185', name: 'Perceval Object Code' },
  { key: '0186', name: 'TrustPoint Object Identifiers' },
  { key: '0187', name: 'Amazon Unique Identification Scheme' },
  { key: '0188', name: 'Corporate Number of The Social Security and Tax Number System' },
  { key: '0189', name: 'European Business Identifier (EBID)' },
  { key: '0190', name: 'Organisatie Indentificatie Nummer (OIN)' },
  { key: '0191', name: 'Company Code (Estonia)' },
  { key: '0192', name: 'Organisasjonsnummer' },
  { key: '0193', name: 'UBL.BE Party Identifier' },
  { key: '0194', name: 'KOIOS Open Technical Dictionary' },
  { key: '0195', name: 'Singapore Nationwide E-lnvoice Framework' },
  { key: '0196', name: 'Icelandic identifier - Íslensk kennitala' },
  { key: '0197', name: 'APPLiA Pl Standard' },
  { key: '0198', name: 'ERSTORG' },
  { key: '0199', name: 'Legal Entity Identifier (LEI)' },
  { key: '0200', name: 'Legal entity code (Lithuania)' },
  { key: '0201', name: 'Codice Univoco Unità Organizzativa iPA' },
  { key: '0202', name: 'Indirizzo di Posta Elettronica Certificata' },
  { key: '0203', name: 'eDelivery Network Participant identifier' },
  { key: '0204', name: 'Leitweg-ID' },
  { key: '0205', name: 'CODDEST' },
  { key: '0206', name: 'Registre du Commerce et de l\'Industrie : RCI' },
  { key: '0207', name: 'PiLog Ontology Codification Identifier (POCI)' },
  { key: '0208', name: 'Numero d\'entreprise / ondernemingsnummer / Unternehmensnummer' },
  { key: '0209', name: 'GS1 identification keys' },
  { key: '0210', name: 'CODICE FISCALE' },
  { key: '0211', name: 'PARTITA IVA' },
  { key: '0212', name: 'Finnish Organization Identifier' },
  { key: '0213', name: 'Finnish Organization Value Add Tax Identifier' },
  { key: '0214', name: 'Tradeplace TradePI Standard' },
  { key: '0215', name: 'Net service ID' },
  { key: '0216', name: 'OVTcode' },
  { key: '0217', name: 'The Netherlands Chamber of Commerce and Industry establishment number' },
  { key: '0218', name: 'Unified registration number (Latvia)' },
  { key: '0219', name: 'Taxpayer registration code (Latvia)' },
  { key: '0220', name: 'The Register of Natural Persons (Latvia)' },
  { key: '0221', name: 'The registered number of the qualified invoice issuer' },
  { key: '0222', name: 'Metadata Registry Support' },
  { key: '0223', name: 'EU based company' },
  { key: '0224', name: 'FTCTC CODE ROUTAGE' },
  { key: '0225', name: 'FRCTC ELECTRONIC ADDRESS' },
  { key: '0226', name: 'FRCTC Particulier' },
  { key: '0227', name: 'NON - EU based company' },
  { key: '0228', name: 'Répertoire des Entreprises et des Etablissements (RIDET)' },
  { key: '0229', name: 'T.A.H.I.T.I (traitement automatique hiérarchisé des institutions de Tahiti et des îles)' },
  { key: '0230', name: 'National e-Invoicing Framework' },
  { key: '0231', name: 'Single taxable company (France)' },
  { key: '0232', name: 'NOBB product number' },
  { key: '0233', name: 'Elnummer' },
  { key: '0234', name: 'Toimitusosoite ID' },
  { key: '0235', name: 'UAE Tax Identification Number (TIN)' },
  { key: '0236', name: 'ToimipaikkalD' },
  { key: '0237', name: 'CPR (Danish person civil registration number)' },
  { key: '0238', name: 'Plateforme.s agréée.s à la facturation électronique (PPF/PDP)' },
  { key: '0239', name: 'EAEU' },
  { key: '0240', name: 'Register of legal persons (in French : Répertoire des personnes morales)' },
]


export const zodValidIsoIcdSchemeIdentifiers = z.enum(
  ISO_ICD_SCHEME_IDENTIFIERS.map((scheme) => scheme.key) as [string, ...string[]]
);