export const ITEM_TYPE_IDENTIFICATION_CODES: { key: string, name: string }[] = [
  { key: "AA", name: "Product version number" },
  { key: "AB", name: "Assembly" },
  { key: "AC", name: "HIBC (Health Industry Bar Code)" },
  { key: "AD", name: "Cold roll number" },
  { key: "AE", name: "Hot roll number" },
  { key: "AF", name: "Slab number" },
  { key: "AG", name: "Software revision number" },
  { key: "AH", name: "UPC (Universal Product Code) Consumer package code (1-5-5)" },
  { key: "AI", name: "UPC (Universal Product Code) Consumer package code (1-5-5-1)" },
  { key: "AJ", name: "Sample number" },
  { key: "AK", name: "Pack number" },
  { key: "AL", name: "UPC (Universal Product Code) Shipping container code (1-2-5-5)" },
  { key: "AM", name: "UPC (Universal Product Code)/EAN (European article number) Shipping container code (1-2-5-5-1)" },
  { key: "AN", name: "UPC (Universal Product Code) suffix" },
  { key: "AO", name: "State label code" },
  { key: "AP", name: "Heat number" },
  { key: "AQ", name: "Coupon number" },
  { key: "AR", name: "Resource number" },
  { key: "AS", name: "Work task number" },
  { key: "AT", name: "Price look up number" },
  { key: "AU", name: "NSN (North Atlantic Treaty Organization Stock Number)" },
  { key: "AV", name: "Refined product code" },
  { key: "AW", name: "Exhibit" },
  { key: "AX", name: "End item" },
  { key: "AY", name: "Federal supply classification" },
  { key: "AZ", name: "Engineering data list" },
  { key: "BA", name: "Milestone event number" },
  { key: "BB", name: "Lot number" },
  { key: "BC", name: "National drug code 4-4-2 format" },
  { key: "BD", name: "National drug code 5-3-2 format" },
  { key: "BE", name: "National drug code 5-4-1 format" },
  { key: "BF", name: "National drug code 5-4-2 format" },
  { key: "BG", name: "National drug code" },
  { key: "BH", name: "Part number" },
  { key: "BI", name: "Local Stock Number (LSN)" },
  { key: "BJ", name: "Next higher assembly number" },
  { key: "BK", name: "Data category" },
  { key: "BL", name: "Control number" },
  { key: "BM", name: "Special material identification code" },
  { key: "BN", name: "Locally assigned control number" },
  { key: "BO", name: "Buyer's colour" },
  { key: "BP", name: "Buyer's part number" },
  { key: "BQ", name: "Variable measure product code" },
  { key: "BR", name: "Financial phase" },
  { key: "BS", name: "Contract breakdown" },
  { key: "BT", name: "Technical phase" },
  { key: "BU", name: "Dye lot number" },
  { key: "BV", name: "Daily statement of activities" },
  { key: "BW", name: "Periodical statement of activities within a bilaterally agreed time period" },
  { key: "BX", name: "Calendar week statement of activities" },
  { key: "BY", name: "Calendar month statement of activities" },
  { key: "BZ", name: "Original equipment number" },
  { key: "CC", name: "Industry commodity code" },
  { key: "CG", name: "Commodity grouping" },
  { key: "CL", name: "Colour number" },
  { key: "CR", name: "Contract number" },
  { key: "CV", name: "Customs article number" },
  { key: "DR", name: "Drawing revision number" },
  { key: "DW", name: "Drawing" },
  { key: "EC", name: "Engineering change level" },
  { key: "EF", name: "Material code" },
  { key: "EMD", name: "EMDN (European Medical Device Nomenclature)" },
  { key: "EN", name: "International Article Numbering Association (EAN)" },
  { key: "FS", name: "Fish species" },
  { key: "GB", name: "Buyer's internal product group code" },
  { key: "GMN", name: "Global model number" },
  { key: "GN", name: "National product group code" },
  { key: "GS", name: "General specification number" },
  { key: "HS", name: "Harmonised system" },
  { key: "IB", name: "ISBN (International Standard Book Number)" },
  { key: "IN", name: "Buyer's item number" },
  { key: "IS", name: "ISSN (International Standard Serial Number)" },
  { key: "IT", name: "Buyer's style number" },
  { key: "IZ", name: "Buyer's size code" },
  { key: "MA", name: "Machine number" },
  { key: "MF", name: "Manufacturer's (producer's) article number" },
  { key: "MN", name: "Model number" },
  { key: "MP", name: "Product/service identification number" },
  { key: "NB", name: "Batch number" },
  { key: "ON", name: "Customer order number" },
  { key: "PD", name: "Part number description" },
  { key: "PL", name: "Purchaser's order line number" },
  { key: "PO", name: "Purchase order number" },
  { key: "PV", name: "Promotional variant number" },
  { key: "QS", name: "Buyer's qualifier for size" },
  { key: "RC", name: "Returnable container number" },
  { key: "RN", name: "Release number" },
  { key: "RU", name: "Run number" },
  { key: "RY", name: "Record keeping of model year" },
  { key: "SA", name: "Supplier's article number" },
  { key: "SG", name: "Standard group of products (mixed assortment)" },
  { key: "SK", name: "SKU (Stock keeping unit)" },
  { key: "SN", name: "Serial number" },
  { key: "SRS", name: "RSK number" },
  { key: "SRT", name: "IFLS (Institut Francais du Libre Service) 5 digit product classification code" },
  { key: "SRU", name: "IFLS (Institut Francais du Libre Service) 9 digit product classification code" },
  { key: "SRV", name: "GS1 Global Trade Item Number" },
  { key: "SRW", name: "EDIS (Energy Data Identification System)" },
  { key: "SRX", name: "Slaughter number" },
  { key: "SRY", name: "Official animal number" },
  { key: "SRZ", name: "Harmonized tariff schedule" },
  { key: "SS", name: "Supplier's supplier article number" },
  { key: "SSA", name: "46 Level DOT Code" },
  { key: "SSB", name: "Airline Tariff 6D" },
  { key: "SSC", name: "Title 49 Code of Federal Regulations" },
  { key: "SSD", name: "International Civil Aviation Administration code" },
  { key: "SSE", name: "Hazardous Materials ID DOT" },
  { key: "SSF", name: "Endorsement" },
  { key: "SSG", name: "Air Force Regulation 71-4" },
  { key: "SSH", name: "Breed" },
  { key: "SSI", name: "Chemical Abstract Service (CAS) registry number" },
  { key: "SSJ", name: "Engine model designation" },
  { key: "SSK", name: "Institutional Meat Purchase Specifications (IMPS) Number" },
  { key: "SSL", name: "Price Look-Up code (PLU)" },
  { key: "SSM", name: "International Maritime Organization (IMO) Code" },
  { key: "SSN", name: "Bureau of Explosives 600-A (rail)" },
  { key: "SSO", name: "United Nations Dangerous Goods List" },
  { key: "SSP", name: "International Code of Botanical Nomenclature (ICBN)" },
  { key: "SSQ", name: "International Code of Zoological Nomenclature (ICZN)" },
  { key: "SSR", name: "International Code of Nomenclature for Cultivated Plants (ICNCP)" },
  { key: "SSS", name: "Distributor's article identifier" },
  { key: "SST", name: "Norwegian Classification system ENVA" },
  { key: "SSU", name: "Supplier assigned classification" },
  { key: "SSV", name: "Mexican classification system AMECE" },
  { key: "SSW", name: "German classification system CCG" },
  { key: "SSX", name: "Finnish classification system EANFIN" },
  { key: "SSY", name: "Canadian classification system ICC" },
  { key: "SSZ", name: "French classification system IFLS5" },
  { key: "ST", name: "Style number" },
  { key: "STA", name: "Dutch classification system CBL" },
  { key: "STB", name: "Japanese classification system JICFS" },
  { key: "STC", name: "European Union dairy subsidy eligibility classification" },
  { key: "STD", name: "GS1 Spain classification system" },
  { key: "STE", name: "GS1 Poland classification system" },
  { key: "STF", name: "Federal Agency on Technical Regulating and Metrology of the Russian Federation" },
  { key: "STG", name: "Efficient Consumer Response (ECR) Austria classification system" },
  { key: "STH", name: "GS1 Italy classification system" },
  { key: "STI", name: "CPV (Common Procurement Vocabulary)" },
  { key: "STJ", name: "IFDA (International Foodservice Distributors Association)" },
  { key: "STK", name: "AHFS (American Hospital Formulary Service) pharmacologic -therapeutic classification" },
  { key: "STL", name: "ATC (Anatomical Therapeutic Chemical) classification system" },
  { key: "STM", name: "CLADIMED (Classification des Dispositifs Médicaux)" },
  { key: "STN", name: "CMDR (Canadian Medical Device Regulations) classification system" },
  { key: "STO", name: "CNDM (Classificazione Nazionale dei Dispositivi Medici)" },
  { key: "STP", name: "UK DM&D (Dictionary of Medicines & Devices) standard coding scheme" },
  { key: "STQ", name: "eCl@ss" },
  { key: "STR", name: "EDMA (European Diagnostic Manufacturers Association) Product Classification" },
  { key: "STS", name: "EGAR (European Generic Article Register)" },
  { key: "STT", name: "GMDN (Global Medical Devices Nomenclature)" },
  { key: "STU", name: "GPI (Generic Product Identifier)" },
  { key: "STV", name: "HCPCS (Healthcare Common Procedure Coding System)" },
  { key: "STW", name: "ICPS (International Classification for Patient Safety)" },
  { key: "STX", name: "MedDRA (Medical Dictionary for Regulatory Activities)" },
  { key: "STY", name: "Medical Columbus" },
  { key: "STZ", name: "NAPCS (North American Product Classification System)" },
  { key: "SUA", name: "NHS (National Health Services) eClass" },
  { key: "SUB", name: "US FDA (Food and Drug Administration) Product Code Classification Database" },
  { key: "SUC", name: "SNOMED CT (Systematized Nomenclature of Medicine-Clinical Terms)" },
  { key: "SUD", name: "UMDNS (Universal Medical Device Nomenclature System)" },
  { key: "SUE", name: "GS1 Global Returnable Asset Identifier, non-serialised" },
  { key: "SUF", name: "IMEI" },
  { key: "SUG", name: "Waste Type (EMSA)" },
  { key: "SUH", name: "Ship's store classification type" },
  { key: "SUI", name: "Emergency fire code" },
  { key: "SUJ", name: "Emergency spillage code" },
  { key: "SUK", name: "IMDG packing group" },
  { key: "SUL", name: "MARPOL Code IBC" },
  { key: "SUM", name: "IMDG subsidiary risk class" },
  { key: "TG", name: "Transport group number" },
  { key: "TSN", name: "Taxonomic Serial Number" },
  { key: "TSO", name: "IMDG main hazard class" },
  { key: "TSP", name: "EU Combined Nomenclature" },
  { key: "TSQ", name: "Therapeutic classification number" },
  { key: "TSR", name: "European Waste Catalogue" },
  { key: "TSS", name: "Price grouping code" },
  { key: "TST", name: "UNSPSC" },
  { key: "TSU", name: "EU RoHS Directive" },
  { key: "UA", name: "Ultimate customer's article number" },
  { key: "UP", name: "UPC (Universal product code)" },
  { key: "VN", name: "Vendor item number" },
  { key: "VP", name: "Vendor's (seller's) part number" },
  { key: "VS", name: "Vendor's supplemental item number" },
  { key: "VX", name: "Vendor specification number" },
  { key: "ZZZ", name: "Mutually defined" },
  { key: "PPI", name: "Phytosanitary Passport identifier" },
]