import { sendEmail } from "@core/lib/email";
import {
  getIncomingCompanyNotificationEmailAddresses,
  getOutgoingCompanyNotificationEmailAddresses,
} from "@peppol/data/company-notification-emails";
import DocumentIncomingNotification from "@peppol/emails/document-incoming-notification";
import DocumentOutgoingNotification from "@peppol/emails/document-outgoing-notification";
import { Attachment } from "postmark";
import { sendSystemAlert } from "@peppol/utils/system-notifications/telegram";
import { getDocumentType } from "@peppol/utils/type-repository/document-types";
import type {
  AnyDocumentType,
  ParsedDocumentOf,
  StoredDocumentType,
} from "@peppol/utils/type-repository/document-types/types";
import {
  buildIncomingDocumentNotificationAttachmentParts,
  buildOutgoingDocumentNotificationAttachmentParts,
} from "@peppol/data/email/document-notification-props";
import { UNNAMED_PARTY } from "@peppol/utils/type-repository/document-types/constants";

function getDocumentUrl(transmittedDocumentId: string) {
  const baseUrl = (process.env.BASE_URL ?? "https://app.recommand.eu").replace(/\/$/, "");
  return `${baseUrl}/transmitted-documents/${transmittedDocumentId}`;
}

export async function sendIncomingDocumentNotifications(options: {
  companyId: string;
  companyName: string;
  type: StoredDocumentType;
  parsedDocument: ParsedDocumentOf<AnyDocumentType> | null;
  xmlDocument: string;
  transmittedDocumentId: string;
  isPlayground?: boolean;
}): Promise<void> {
  try {
    const notificationEmails =
      await getIncomingCompanyNotificationEmailAddresses(options.companyId);

    if (notificationEmails.length === 0) {
      return;
    }

    const documentType = getDocumentType(options.type);
    if (documentType?.email?.areEmailNotificationsSupported === false) {
      return;
    }
    const { documentNumber, amount, currency, senderName, receiverName } =
      documentType?.email && options.parsedDocument
        ? documentType.email.extractDocumentDetails(options.parsedDocument)
        : {};
    const documentTypeLabel = documentType?.translatableTitle ?? "Document";
    let subject = documentNumber
      ? `New ${documentTypeLabel} Received: ${documentNumber}`
      : `New ${documentTypeLabel} Received - ${options.companyName}`;

    if (options.isPlayground) {
      subject = `[PLAYGROUND/TEST] ${subject}`;
    }

    const shouldIncludePdf = notificationEmails.some(
      (notificationEmail) => notificationEmail.includeAutoGeneratedPdfIncoming
    );
    const shouldIncludeJson = notificationEmails.some(
      (notificationEmail) => notificationEmail.includeDocumentJsonIncoming
    );
    const {
      embeddedAttachments,
      xmlAttachment,
      autoGeneratedPdfAttachment,
      documentJsonAttachment,
    } = await buildIncomingDocumentNotificationAttachmentParts({
      transmittedDocumentId: options.transmittedDocumentId,
      companyId: options.companyId,
      companyName: options.companyName,
      type: options.type,
      parsedDocument: options.parsedDocument,
      xmlDocument: options.xmlDocument,
      includeAutoGeneratedPdf: shouldIncludePdf,
      includeDocumentJson: shouldIncludeJson,
    });

    for (const notificationEmail of notificationEmails) {
      try {
        const extraAttachments: Attachment[] = [];
        if (
          notificationEmail.includeAutoGeneratedPdfIncoming &&
          autoGeneratedPdfAttachment
        ) {
          extraAttachments.push(autoGeneratedPdfAttachment);
        }
        if (
          notificationEmail.includeDocumentJsonIncoming &&
          documentJsonAttachment
        ) {
          extraAttachments.push(documentJsonAttachment);
        }

        const attachments = [
          ...embeddedAttachments,
          ...(xmlAttachment ? [xmlAttachment] : []),
          ...extraAttachments,
        ];

        await sendEmail({
          to: notificationEmail.email,
          subject,
          email: DocumentIncomingNotification({
            companyName: options.companyName,
            senderName: senderName ?? UNNAMED_PARTY,
            documentType: documentTypeLabel,
            documentNumber: documentNumber,
            amount: amount,
            currency: currency,
            documentUrl: getDocumentUrl(options.transmittedDocumentId),
          }),
          attachments,
        });
      } catch (error) {
        console.error(
          `Failed to send incoming document notification to ${notificationEmail.email}:`,
          error
        );
        sendSystemAlert(
          "Document Notification Sending Failed",
          `Failed to send incoming document notification to ${notificationEmail.email}.`,
          "error"
        );
      }
    }
  } catch (error) {
    console.error("Failed to send incoming document notifications:", error);
    sendSystemAlert(
      "Document Notification Sending Failed",
      `Failed to send incoming document notifications.`,
      "error"
    );
  }
}

export async function sendOutgoingDocumentNotifications(options: {
  companyId: string;
  companyName: string;
  type: StoredDocumentType;
  parsedDocument: ParsedDocumentOf<AnyDocumentType> | null;
  xmlDocument: string | null;
  transmittedDocumentId: string;
  isPlayground?: boolean;
}): Promise<void> {
  try {
    const notificationEmails =
      await getOutgoingCompanyNotificationEmailAddresses(options.companyId);

    if (notificationEmails.length === 0) {
      return;
    }

    const documentType = getDocumentType(options.type);
    if (documentType?.email?.areEmailNotificationsSupported === false) {
      return;
    }
    const { documentNumber, amount, currency, receiverName } =
      documentType?.email && options.parsedDocument
        ? documentType.email.extractDocumentDetails(options.parsedDocument)
        : {};
    const documentTypeLabel = documentType?.translatableTitle ?? "Document";
    let subject = documentNumber
      ? `${documentTypeLabel} Sent Successfully: ${documentNumber}`
      : `${documentTypeLabel} Sent Successfully - ${options.companyName}`;

    if (options.isPlayground) {
      subject = `[PLAYGROUND/TEST] ${subject}`;
    }

    const shouldIncludePdf = notificationEmails.some(
      (notificationEmail) => notificationEmail.includeAutoGeneratedPdfOutgoing
    );
    const shouldIncludeJson = notificationEmails.some(
      (notificationEmail) => notificationEmail.includeDocumentJsonOutgoing
    );
    const {
      embeddedAttachments,
      xmlAttachment,
      autoGeneratedPdfAttachment,
      documentJsonAttachment,
    } = await buildOutgoingDocumentNotificationAttachmentParts({
      transmittedDocumentId: options.transmittedDocumentId,
      companyId: options.companyId,
      companyName: options.companyName,
      type: options.type,
      parsedDocument: options.parsedDocument,
      xmlDocument: options.xmlDocument,
      includeAutoGeneratedPdf: shouldIncludePdf,
      includeDocumentJson: shouldIncludeJson,
    });

    for (const notificationEmail of notificationEmails) {
      try {
        const extraAttachments: Attachment[] = [];
        if (
          notificationEmail.includeAutoGeneratedPdfOutgoing &&
          autoGeneratedPdfAttachment
        ) {
          extraAttachments.push(autoGeneratedPdfAttachment);
        }
        if (
          notificationEmail.includeDocumentJsonOutgoing &&
          documentJsonAttachment
        ) {
          extraAttachments.push(documentJsonAttachment);
        }

        const attachments = [
          ...embeddedAttachments,
          ...(xmlAttachment ? [xmlAttachment] : []),
          ...extraAttachments,
        ];

        await sendEmail({
          to: notificationEmail.email,
          subject,
          email: DocumentOutgoingNotification({
            companyName: options.companyName,
            recipientName: receiverName ?? UNNAMED_PARTY,
            documentType: documentTypeLabel,
            documentNumber: documentNumber,
            amount: amount,
            currency: currency,
            documentUrl: getDocumentUrl(options.transmittedDocumentId),
          }),
          attachments,
        });
      } catch (error) {
        console.error(
          `Failed to send outgoing document notification to ${notificationEmail.email}:`,
          error
        );
        sendSystemAlert(
          "Document Notification Sending Failed",
          `Failed to send outgoing document notification to ${notificationEmail.email}.`,
          "error"
        );
      }
    }
  } catch (error) {
    console.error("Failed to send outgoing document notifications:", error);
    sendSystemAlert(
      "Document Notification Sending Failed",
      `Failed to send outgoing document notifications.`,
      "error"
    );
  }
}
