import "zod-openapi/extend";
import { Server } from "@recommand/lib/api";
import getCompaniesServer, { type GetCompanies } from "./get-companies";
import getCompanyServer, { type GetCompany } from "./get-company";
import createCompanyServer, { type CreateCompany } from "./create-company";
import updateCompanyServer, { type UpdateCompany } from "./update-company";
import deleteCompanyServer, { type DeleteCompany } from "./delete-company";
import verifyCompanyServer, { type VerifyCompany } from "./verify-company";
import verifyCompanyByContractServer, { type VerifyCompanyByContract } from "./verify-company-by-contract";
import enterpriseDataServer, { type GetCompanyEnterpriseData } from "./enterprise-data";
import vatLookupServer, { type VatLookup } from "./vat-lookup";
import companyIdentifiersServer, { type CompanyIdentifiers } from "./identifiers";
import companyDocumentTypesServer, { type CompanyDocumentTypes } from "./document-types";
import companyNotificationEmailAddressesServer, { type CompanyNotificationEmailAddresses } from "./notification-email-addresses";
import companyVerificationServer, { type CompanyVerification } from "./verification";

export type Companies = GetCompanies | GetCompany | CreateCompany | UpdateCompany | DeleteCompany | VerifyCompany | VerifyCompanyByContract | GetCompanyEnterpriseData | VatLookup | CompanyIdentifiers | CompanyDocumentTypes | CompanyNotificationEmailAddresses | CompanyVerification;

const server = new Server();
server.route("/", getCompaniesServer);
server.route("/", getCompanyServer);
server.route("/", createCompanyServer);
server.route("/", updateCompanyServer);
server.route("/", deleteCompanyServer);
server.route("/", verifyCompanyServer);
server.route("/", verifyCompanyByContractServer);
server.route("/", enterpriseDataServer);
server.route("/", vatLookupServer);
server.route("/", companyIdentifiersServer);
server.route("/", companyDocumentTypesServer);
server.route("/", companyNotificationEmailAddressesServer);
server.route("/", companyVerificationServer);
export default server;