import { getFranceCdarPhaseForStatus } from "@peppol/utils/parsing/france-cdar/schemas";
import type { ParsedDocument } from "./parsed";
import type { ParsedOrUnknownDocumentType } from "./types";

/**
 * Whether a stored document counts towards the team's document usage.
 *
 * A customer pays for documents and for the business answers to them, not for
 * the messages the network and the platforms exchange to move them. A message
 * level response is a transport receipt and is never billed. A French lifecycle
 * status (CDAR) is billed when it belongs to the processing phase, where a buyer
 * or seller decided something about the invoice (approved, disputed, refused,
 * collected), and not when it belongs to the transmission phase, where a
 * platform recorded that a file was submitted, received, made available or
 * technically rejected. The transmission statuses are the French counterpart of
 * a message level response, and most of them are generated by a platform without
 * the customer doing anything.
 *
 * The rule applies in both directions, so the party sending a business status
 * and the party receiving it are treated alike, exactly as for an invoice.
 */
export function isBillableDocument(
  type: ParsedOrUnknownDocumentType,
  parsed: ParsedDocument | null | undefined,
): boolean {
  if (type === "messageLevelResponse") {
    return false;
  }
  if (type === "frenchInvoicingCdar") {
    const cdar = parsed as { phase?: string; statusCode?: string } | null | undefined;
    const phase =
      cdar?.phase ??
      (cdar?.statusCode
        ? getFranceCdarPhaseForStatus(cdar.statusCode as Parameters<typeof getFranceCdarPhaseForStatus>[0])
        : undefined);
    // An unparseable status cannot be shown to be a business answer, so it is not
    // charged as one.
    return phase === "23";
  }
  return true;
}
