import { z } from "zod";
import "zod-openapi/extend";
import { sendInvoiceSchema } from "./invoice/schemas";
import { sendCreditNoteSchema } from "./creditnote/schemas";
import { sendSelfBillingInvoiceSchema } from "./self-billing-invoice/schemas";
import { sendSelfBillingCreditNoteSchema } from "./self-billing-creditnote/schemas";
import { sendMessageLevelResponseSchema } from "./message-level-response/schemas";

export const DocumentType = {
  INVOICE: "invoice",
  CREDIT_NOTE: "creditNote",
  SELF_BILLING_INVOICE: "selfBillingInvoice",
  SELF_BILLING_CREDIT_NOTE: "selfBillingCreditNote",
  MESSAGE_LEVEL_RESPONSE: "messageLevelResponse",
  XML: "xml",
} as const;

export const documentTypeSchema = z
  .enum([
    DocumentType.INVOICE,
    DocumentType.CREDIT_NOTE,
    DocumentType.SELF_BILLING_INVOICE,
    DocumentType.SELF_BILLING_CREDIT_NOTE,
    DocumentType.MESSAGE_LEVEL_RESPONSE,
    DocumentType.XML,
  ])
  .openapi({
    description: "The type of document.",
    example: DocumentType.INVOICE,
  });

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

const sendDocumentBaseSchema = z.object({
  recipient: z.string().nullable().openapi({
    description:
      "The Peppol address of the recipient. If null, the document will be sent via email only (requires `email.to`).",
    example: "0208:987654321",
  }),
  email: z
    .object({
      when: z
        .enum(["always", "on_peppol_failure"])
        .default("on_peppol_failure")
        .openapi({
          description:
            "When to send the email. If the provided Peppol recipient is null, email becomes the primary delivery method and emails are always sent.",
        }),
      to: z.array(z.string()).openapi({
        description: "The email addresses to send the document to.",
        example: ["support@recommand.eu"],
      }),
      subject: z.string().optional().openapi({
        description:
          "The subject of the email. If not provided, the subject will be autogenerated based on the document type.",
        example: "Invoice SI-001",
      }),
      htmlBody: z.string().optional().openapi({
        description:
          "The HTML body of the email. If not provided, the body will be autogenerated based on the document type.",
        example: "Dear customer, you can find your invoice attached.",
      }),
    })
    .optional()
    .openapi({
      ref: "Email",
      description:
        "Email delivery options. When Peppol recipient is provided, email is optional and you can choose to always send the email, or only when Peppol delivery fails. When Peppol recipient is null, email becomes the primary delivery method and `email.to` is required. Each sent email is counted towards your document quota.",
    }),
  pdfGeneration: z
    .object({
      enabled: z.boolean().default(false).openapi({
        description:
          "Whether to generate a PDF of the document and include it as an embedded attachment.",
      }),
      filename: z
        .string()
        .refine((name) => !name.includes("/") && !name.includes("\\"), {
          message: "Filename must not include path separators.",
        })
        .optional()
        .openapi({
          description:
            "Optional filename to use for the generated PDF attachment. Defaults to a filename derived from the document number (e.g. invoice-001.pdf).",
          example: "INV-2024-001.pdf",
        }),
    })
    .optional()
    .openapi({
      ref: "PDFGeneration",
      description:
        "Optionally generate a PDF of the document and include it as an embedded attachment (also included in email attachments when email sending is enabled). Not supported for message level responses or raw XML documents.",
    }),
  doctypeId: z.string().optional().openapi({
    description:
      'The document type identifier. Not required, only used when documentType is "xml". For supported document types, the doctypeId can be detected automatically from your XML document, if that\'s not the case you can provide it manually.',
    example:
      "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1",
  }),
  processId: z.string().optional().openapi({
    description:
      'The process identifier. For supported document types the processId can be detected automatically; provide it manually when documentType is "xml" or to override the default.',
    example: "urn:fdc:peppol.eu:2017:poacc:billing:01:1.0",
  }),
});

export const sendInvoiceRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.INVOICE),
    document: sendInvoiceSchema,
  })
  .openapi({
    ref: "SendInvoiceRequest",
    title: "Send Invoice",
    description: "Request to send an invoice via Peppol and/or email.",
  });

export const sendCreditNoteRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.CREDIT_NOTE),
    document: sendCreditNoteSchema,
  })
  .openapi({
    ref: "SendCreditNoteRequest",
    title: "Send Credit Note",
    description: "Request to send a credit note via Peppol and/or email.",
  });

export const sendSelfBillingInvoiceRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.SELF_BILLING_INVOICE),
    document: sendSelfBillingInvoiceSchema,
  })
  .openapi({
    ref: "SendSelfBillingInvoiceRequest",
    title: "Send Self-Billing Invoice",
    description:
      "Request to send a self-billing invoice via Peppol and/or email.",
  });

export const sendSelfBillingCreditNoteRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.SELF_BILLING_CREDIT_NOTE),
    document: sendSelfBillingCreditNoteSchema,
  })
  .openapi({
    ref: "SendSelfBillingCreditNoteRequest",
    title: "Send Self-Billing Credit Note",
    description:
      "Request to send a self-billing credit note via Peppol and/or email.",
  });

export const sendMessageLevelResponseRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.MESSAGE_LEVEL_RESPONSE),
    document: sendMessageLevelResponseSchema,
  })
  .openapi({
    ref: "SendMessageLevelResponseRequest",
    title: "Send Message Level Response",
    description: "Request to send a message level response via Peppol.",
  });

export const sendXmlRequestSchema = sendDocumentBaseSchema
  .extend({
    documentType: z.literal(DocumentType.XML),
    document: z.string().openapi({
      title: "XML",
      description: "Raw UBL XML document as a string.",
    }),
  })
  .openapi({
    ref: "SendXmlRequest",
    title: "Send Raw XML",
    description:
      "Request to send a pre-built UBL XML document via Peppol and/or email.",
  });

export const sendDocumentSchema = z
  .discriminatedUnion("documentType", [
    sendInvoiceRequestSchema,
    sendCreditNoteRequestSchema,
    sendSelfBillingInvoiceRequestSchema,
    sendSelfBillingCreditNoteRequestSchema,
    sendMessageLevelResponseRequestSchema,
    sendXmlRequestSchema,
  ])
  .openapi({
    ref: "SendDocumentRequest",
    title: "Send Document Request",
    description:
      "Request body for sending a document. The concrete shape is selected by the `documentType` discriminator.",
  });

export type SendDocument = z.infer<typeof sendDocumentSchema>;
export type SendInvoiceRequest = z.infer<typeof sendInvoiceRequestSchema>;
export type SendCreditNoteRequest = z.infer<typeof sendCreditNoteRequestSchema>;
export type SendSelfBillingInvoiceRequest = z.infer<
  typeof sendSelfBillingInvoiceRequestSchema
>;
export type SendSelfBillingCreditNoteRequest = z.infer<
  typeof sendSelfBillingCreditNoteRequestSchema
>;
export type SendMessageLevelResponseRequest = z.infer<
  typeof sendMessageLevelResponseRequestSchema
>;
export type SendXmlRequest = z.infer<typeof sendXmlRequestSchema>;
